### ISSUE TITLE
Adding to C# Window Form.Net Application

### ISSUE THREAD

**Issue by threetoedsloth6** [Mecanik/Anti-DebugNET#4]
Hi I been trying to implement this for weeks on my window form application but doesn't seem to be working at all is there other parameters i need for it to work on a C# Window Form.Net application or should it just work 

Thank.

**Comment by Mecanik** [comment]
Hello, well it should not take you so long that's for sure. It is literally copy/paste scenario.

If you wish get in touch with me via Email and I can have a look for you, so you don't publish your code here.

Thanks
