### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by CodeFanaticX** [Mecanik/Anti-DebugNET#6]
Hi. Already build this but still no idea how I can use this to my app.
Is there any tutorial?

**Comment by Mecanik** [comment]
Hi, try to debug your app to see the effect.

**Comment by CodeFanaticX** [comment]
> Hi, try to debug your app to see the effect.

Ahm I still don't get it. Should I just put the Anti-DebugNET.exe in my project? then run it?
