### ISSUE TITLE
Crash function

### ISSUE THREAD

**Issue by bbday** [Mecanik/Anti-DebugNET#7]
is it possible have example of something that will crash application as you explain ? (instead use .kill()/.exit() easy to find in code)

i thought something with winapi cause unmanaged code should be better !?!?

thanks

**Comment by Mecanik** [comment]
> is it possible have example of something that will crash application as you explain ? (instead use .kill()/.exit() easy to find in code)
> 

Sure, you can crash your app in any way you want, just cause an exception or something. Just look at: https://stackoverflow.com/questions/56385719/how-to-make-c-sharp-application-crash-with-an-accessviolationexception

For historical reference:

```
int[] array = new int[1];
fixed (int* ptr = array)
{
      ptr[2000000] = 42;
}
```

```
[DllImport("kernel32.dll")]
static extern void RaiseException(uint dwExceptionCode, uint dwExceptionFlags,  uint nNumberOfArguments, IntPtr lpArguments);

void start()
{
    RaiseException(0xC0000005, 0, 0, new IntPtr(1));
}
```

> i thought something with winapi cause unmanaged code should be better !?!?
> 

Yes, it is of course. But even this can be easily traced... so I recommend going the hard way and look into system calls. I haven't had the time to add system calls support yet. And frankly, nobody is supporting the work so... you are on your own.

**Comment by bbday** [comment]
thank you so much

**Comment by enit9747** [comment]
> Yes, it is of course. But even this can be easily traced... so I recommend going the hard way and look into system calls. I haven't had the time to add system calls support yet. And frankly, nobody is supporting the work so... you are on your own.

By crashing using system calls, do you mean something like this:
```csharp
[DllImport("ntdll.dll")]
public static extern uint NtRaiseHardError(
uint ErrorStatus,
uint NumberOfParameters,
uint UnicodeStringParameterMask,
IntPtr Parameters,
uint ValidResponseOption,
out uint Response);

void crashApp()
{
const uint ERROR_STATUS_BUFFER_OVERFLOW = 0xC0000023;
uint response;
NtRaiseHardError(ERROR_STATUS_BUFFER_OVERFLOW, 0, 0, IntPtr.Zero, 6, out response);
}
```

**Comment by Mecanik** [comment]
> > Yes, it is of course. But even this can be easily traced... so I recommend going the hard way and look into system calls. I haven't had the time to add system calls support yet. And frankly, nobody is supporting the work so... you are on your own.
> 
> By crashing using system calls, do you mean something like this:
> 
> ```cs
> [DllImport("ntdll.dll")]
> public static extern uint NtRaiseHardError(
> uint ErrorStatus,
> uint NumberOfParameters,
> uint UnicodeStringParameterMask,
> IntPtr Parameters,
> uint ValidResponseOption,
> out uint Response);
> 
> void crashApp()
> {
> const uint ERROR_STATUS_BUFFER_OVERFLOW = 0xC0000023;
> uint response;
> NtRaiseHardError(ERROR_STATUS_BUFFER_OVERFLOW, 0, 0, IntPtr.Zero, 6, out response);
> }
> ```

No. This is a normal imported WinAPI call. The reason I haven't added system calls yet is because it's too much of a mess in C#, each call needs to be built per platform.

You can use something like https://github.com/plackyhacker/Sys-Calls which has examples, but bear in mind that AV's will quickly mark them as virus.

Long story short, C#/.NET is an easy to use language, but sucks in many, many aspects.

**Comment by bbday** [comment]
maybe with some obfuscation you can reduce antivirus trigger (idea, didnt try it)

**Comment by enit9747** [comment]
> No. This is a normal imported WinAPI call. The reason I haven't added system calls yet is because it's too much of a mess in C#, each call needs to be built per platform.
> 
> You can use something like https://github.com/plackyhacker/Sys-Calls which has examples, but bear in mind that AV's will quickly mark them as virus.
> 
> Long story short, C#/.NET is an easy to use language, but sucks in many, many aspects.

I only use this for windows either way so for me this does the job.
