### ISSUE TITLE
AntiDump issue x64

### ISSUE THREAD

**Issue by bbday** [Mecanik/Anti-DebugNET#8]
Look like there is issue with AntiDump() when i force x64 solution

var dwpeheader          = System.Runtime.InteropServices.Marshal.ReadInt32((IntPtr)(base_address.ToInt32() + 0x3C));
**Aritmetic overflow**

Is it possible to fix this function for x64 runtime?
thanks

**Comment by Mecanik** [comment]
> System.Runtime.InteropServices.Marshal.ReadInt32

Yes, well x32 bit address is smaller than x64 address. As you can see the function called is ReadInt32, so try to use ReadInt64 instead.
